language: node_js
sudo: false
dist: trusty
node_js: '10'
addons:
  firefox: latest
  chrome: stable

before_script:
  - >-
  npm run format && git diff --exit-code || (echo -e '\n\033[31mERROR:\033[0m
  Project is not formatted. Please run "npm run format".' && false)

script:
  - npm run lint
  - npm test
