language: node_js
sudo: false
dist: trusty
node_js: '10'
addons:
  firefox: latest
  chrome: stable
script:
  - npm run build
  - npm run format && git diff --exit-code || (echo -e '\n\033[31mERROR:\033[0mProject is not formatted. Please run "npm run format".' && false)
  - npm run lint
  - npm run build:tests
  - npm test
env:
  global:
  - secure: XNVuIPbNtOhJ5HpxO01i+pDNZbDK53Q/Yx+gGWKays8SyPBPqSGuaqxbrbWRQiCb9OkflVfIynvHCI9Wmg8ZcrQRntFcVI7UMkVjxH+RzqVeRIQnTeS4Q1yre+rlQNWNXQUTIQf40ydtv90KBkKRbkT07WtbCIxrHPN7nOuXJGRooF194GCHjOepi0DGzGubVflzsVD9JiAmxc1ExqBKpRWxycN4KYoFjGTa1KZZilJUn51WQZtE4TzBgA+fEHklf9AOFTGnwCLnQasJkDQclgbdBRjBqTf86+k1YHEGsmzk32En/oW7WodOB3CtbW9vQHq8MEX+/colOXa+YXFKvgq0E+u8g0rxgF/VaRUZn3AnJBXoYHqliysVK/pumBsXJRgjYFDoPFctJB2V2dOJS3lSO+cAQQLsDs5lnkuKzkVnANJgJ2BVwU+7lqILnadKB3q7FUUvPBUMp0yjFAW9Gx63dJUMwToFYeH+vwDPaaC8GYASDa8nJNHo3ql9rQz64CDnnAa07w/u2/JBuNl0NOa2XLfAC5yz0YR6exPG4qfqRenV+M6nsi9djIbkjQBHNxhUU15Ao/Wjiw0/hhE+L47yUUAa5dhGgFZr/f4x793Bk6Dm6PU+Jre+SweHcE8X/pqc4VwLMnYYin97qdoQNaDmcvSRVD8q3y8grHI1O/A=
  - secure: I71Y1U98rWiwMBDgeBA0ZB724g68N6eotr70cm1y2XYtJgW7DHCicDKIagVx1uslJxnEizUVNGZVPOM9oS8KYD/55Tgl5oMnBEydoz3peXlL1cdIZf3eoLihiefA3DrU+Y7rp/b29qKjY/HP/OPVJUuK9oco2RkgQhWsNoQje9yoaKGuTgClcfjBcDi4nmb30HSI+NDJU33lcbOEALQyT1U3s4EFHY76XtAbxYEpcAiXkZEEWgoZTzC06wUbEXok4iulFxjStMwTWr1wsEA+VPJxhV0YcJILZWRnZj7f7slMu6ik/kk6St4uNd/yf6G6X9GkMTj4NbXFINyvydsoomsre+O2MmdBAmUGi6N1SnmchayODKSYt5JT8TdKlXqYsOVAzYoZKG7oH73GNzhHNy5pqEhSPsM9mVveMfYdg/BSPJP21rsUwMfxfFQc4yn+qWPjH4FAch5QHT3bKR3t7gmrv4YX3R0Ftg8lwCSSC1Bz8QJvzCQ1O9IZtNT91mAxaEd9Y8kz6zeebkSu+qnv3lksTc4/Xfs8BFOUb/e8kZQd2GM90Fg+Qdnnr09LP2wpGlOhk+47SntAaicXSBHHPknXL6kQDVSamyM+vrDraXw4tgQB/q/WSVSbWVg3g8VrKHZ3fle/vWgHt6wC4TM+o+SS0BznADumDSDIzsKtvlY=
