name: auto-format

on:
  push:
    branches: master

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
          node-version: 10

    - name: NPM install
      # Don't run postinstall because we don't need to install sub-packages.
      run: npm ci --ignore-scripts

    - name: Format
      run: npm run format
    
    - name: Check if format produces git diff
      id: ifChange
      run: git diff --exit-code || echo "::set-output name=changed::yes"

    - name: Create PR
      if: steps.ifChange.outputs.changed == 'yes'
      uses: peter-evans/create-pull-request@v1.5.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COMMIT_MESSAGE: Auto-format
        # TODO Find or make an account that is whitelisted to not trigger the CLA check.
        COMMIT_AUTHOR_EMAIL: format-bot@polymer-project.org
        COMMIT_AUTHOR_NAME: Polymer GitHub Actions Robot
        PULL_REQUEST_TITLE: Auto-format master branch
        PULL_REQUEST_BODY: This PR was auto generated by the auto-format GitHub action.
        PULL_REQUEST_REVIEWERS: aomarks,azakus,e111077,asyncliz
        PULL_REQUEST_BRANCH: auto-format-action
        BRANCH_SUFFIX: none
        LABELS: "Ready for Google"
