name: auto-format

on:
  push:
    branches: master

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
          node-version: 10

    - name: NPM install
      # Don't run postinstall because we don't need to install sub-packages.
      run: npm ci --ignore-scripts

    - name: Format
      run: npm run format
    
    - name: Check if format produces git diff
      id: ifChange
      run: git diff --exit-code || echo "::set-output name=changed::yes"

    - name: Create PR
      if: steps.ifChange.outputs.changed == 'yes'
      uses: peter-evans/create-pull-request@v1.7.3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Auto-format
        # TODO Find or make an account that is whitelisted to not trigger the CLA check.
        author-email: format-bot@polymer-project.org
        author-name: Polymer GitHub Actions Robot
        title: Auto-format master branch
        body: This PR was auto generated by the auto-format GitHub action.
        reviewers: aomarks,azakus,e111077,asyncliz
        branch: auto-format-action
        branch-suffix: none
        labels: "Ready for Google"
