name: Test Push

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 10
      uses: actions/setup-node@v1
      with:
        node-version: 10
    - name: npm install
      run: npm ci

    # - name: check if formatted
    #   run: npm run format && git diff --exit-code || (echo -e '\n\033[31mERROR:\033[0mProject is not formatted. Please run "npm run format".' && false)

    # - name: check lint
    #   run: npm run lint

    - name: build tests
      run: npm run buid:tests

    - name: run tests
      run: npm test
      env:
        GITHUB_CI_OS: ${{ matrix.os }}
