name: Test Push

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        # os: [windows-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 10
      uses: actions/setup-node@v1
      with:
        node-version: 10
    - name: npm install
      run: npm ci

    - name: build styles and components
      if: matrix.os != 'windows-latest'
      run: npm run build

    - name: build styles and components (windows)
      if: matrix.os == 'windows-latest'
      run: npm run build:windows

    # - name: check if formatted
    #   run: npm run format && git diff --exit-code || (echo -e '\n\033[31mERROR:\033[0mProject is not formatted. Please run "npm run format".' && false)

    # - name: check lint
    #   run: npm run lint

    - name: build tests
      run: npm run build:tests

    - name: run tests
      run: npm test
      timeout-minutes: 5
      env:
        GITHUB_CI_OS: ${{ matrix.os }}
